name: Deploy Flask SQS App

on:
  push:
    branches:
      - main
    paths:
      - 'flask-sqs-service/**'
                                
env:
  ECS_CLUSTER = "proj-aws-ecs-cicd-ecs-cluster"
  ECR_SQS_REPO = "proj-aws-ecs-cicd-sqs-ecr"
  SQS_TASK_DEF = "proj-aws-ecs-cicd-sqs-svc"
  SQS_ECS_SERVICE = "proj-aws-ecs-cicd-sqs-svc"
  SQS_CONTAINER_NAME = "proj-aws-ecs-cicd-sqs-svc-container"

jobs:
   deploy:
     name: Deploy
     runs-on: ubuntu-latest

     steps:
     - name: Checkout
       uses: actions/checkout@v3

     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: us-east-1

     - name: Login to Amazon ECR
       id: login-ecr
       uses: aws-actions/amazon-ecr-login@v1

     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2

     - name: Build and push Docker image to Amazon ECR
       id: build-image
       uses: docker/build-push-action@v6
       with:
         context: ./flask-sqs-service
         push: true
         tags: |
           ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_SQS_REPO }}:${{ github.sha }}
           ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_SQS_REPO }}:latest
         platforms: linux/amd64
         provenance: false

     - name: Download task definition
       run: |
         aws ecs describe-task-definition --task-definition ${{ env.SQS_TASK_DEF }} --query taskDefinition > task-definition.json

     - name: Fill in the new image ID in the Amazon ECS task definition
       id: task-def
       uses: aws-actions/amazon-ecs-render-task-definition@v1
       with:
         task-definition: task-definition.json
         container-name: ${{ env.SQS_CONTAINER_NAME }}
         image: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_SQS_REPO }}:${{ github.sha }}

     - name: Deploy Amazon ECS task definition
       uses: aws-actions/amazon-ecs-deploy-task-definition@v1
       with:
         task-definition: ${{ steps.task-def.outputs.task-definition }}
         service: ${{ env.SQS_ECS_SERVICE }}
         cluster: ${{ env.ECS_CLUSTER }}
         wait-for-service-stability: true